hospitals:
  - id: kmugh
    enabled: true
    adapter: kmugh
    region: 高雄
    hospital_name: 高雄醫學大學附設醫院
    branch_name: 岡山醫院
    departments:
      - 心臟血管內科
      - 肝膽內科
    schedule_url: https://www.kmugh.org.tw/web/kmugh/MedicalService/OPDSchedule
  - id: edah-main
    enabled: true
    adapter: edah_pdf
    region: 高雄
    hospital_name: 義大醫療財團法人
    branch_name: 義大醫院
    departments: []
    schedule_url: https://edhg.blob.core.windows.net/upload/userfile/Download/51/EDAH_NEW.pdf
  - id: edah-cancer
    enabled: true
    adapter: edah_pdf
    region: 高雄
    hospital_name: 義大醫療財團法人
    branch_name: 義大癌治療醫院
    departments: []
    schedule_url: https://edhg.blob.core.windows.net/upload/userfile/Download/51/EDCH_NEW.pdf
  - id: edah-dachang
    enabled: true
    adapter: edah_pdf
    region: 高雄
    hospital_name: 義大醫療財團法人
    branch_name: 義大大昌醫院
    departments: []
    schedule_url: https://edhg.blob.core.windows.net/upload/userfile/Download/51/EDDH_NEW.pdf
  - id: shinkao
    enabled: true
    adapter: shinkao
    region: 高雄
    hospital_name: 新高醫院
    branch_name: 總院
    departments: []
    schedule_url: https://www.shinkaohosp.com.tw/schedule.aspx
  - id: pingtung-mohw
    enabled: true
    adapter: pingtung_mohw
    region: 屏東
    hospital_name: 衛生福利部屏東醫院
    branch_name: 總院
    departments: []
    schedule_url: https://www.pntn.mohw.gov.tw/?aid=602&iid=2
  - id: cgmh-kaohsiung
    enabled: false
    adapter: cgmh_text
    region: 高雄
    hospital_name: 高雄長庚紀念醫院
    branch_name: 總院
    departments: []
    schedule_url: https://register.cgmh.org.tw/OpTimeSheet/250429004_upload.pdf
  - id: cgmh-datong
    enabled: true
    adapter: cgmh_image
    region: 高雄
    hospital_name: 高雄市立大同醫院
    branch_name: 總院
    departments: []
    schedule_url: https://register.cgmh.org.tw/OpTimeSheet/260421001W_upload.pdf
  - id: antai
    enabled: false
    adapter: antai_image
    region: 屏東
    hospital_name: 安泰醫療社團法人安泰醫院
    branch_name: 總院
    departments: []
    schedule_url: https://www.tsmh.org.tw/sites/web_dg/show_web_page.php?edsno=1003
  - id: ptvgh
    enabled: true
    adapter: ptvgh_pdf
    region: 屏東
    hospital_name: 屏東榮民總醫院
    branch_name: 總院
    departments: []
    schedule_url: https://www.ptvgh.gov.tw/cp.aspx?n=2EA7048AC15C840A
